### ISSUE TITLE
GenerateAvroJavaTask custom source does not work

### ISSUE THREAD

**Issue by saeedansari** [commercehub-oss/gradle-avro-plugin#44]
Hi,
I am using avro plugin to generate java classes from a folder in build directory.

```groovy
task generateAvro(type: com.commercehub.gradle.plugin.avro.GenerateAvroJavaTask) {
    source("${buildDir}/avsc")
    outputDir = file("dest/avro")
}
compileJava.source(generateAvro.outputs)
```
avsc directory is created in `buildDir` before running generateAvro task. But I do not get any java class generated or any error.

**Comment by davidmc24** [comment]
If you run the build with "--info", does it show that the `generateAvro` task has run?  Is it marked as "NO-SOURCE" or "SKIPPED"?  If it ran, what output did it produce?

Here's an example of the type of output I'm looking for:
```
> Task :generateAvroJava
Putting task artifact state for task ':generateAvroJava' into context took 0.0 secs.
Up-to-date check for task ':generateAvroJava' took 0.021 secs. It is not up-to-date because:
  Output property 'outputDir' file /Users/dcarr/repos/gradle-avro-plugin-test/build/generated-main-avro-java has been removed.
  Output property 'outputDir' file /Users/dcarr/repos/gradle-avro-plugin-test/build/generated-main-avro-java/example has been removed.
  Output property 'outputDir' file /Users/dcarr/repos/gradle-avro-plugin-test/build/generated-main-avro-java/example/Breed.java has been removed.
Found 2 files
Processed src/main/avro/Breed.avsc
Processed src/main/avro/Cat.avsc

:generateAvroJava (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 0.539 secs.
```

**Comment by saeedansari** [comment]
Well, it turns out that at the time of running `generateAvro` task, avsc file is not generated correctly. I am using another task to generate avsc file before running generateAvro.

Thank you!

**Comment by NavyaGarg** [comment]
Hello,
I am using avro gradle plugin to generate java classes.

task generateAvro(type: com.commercehub.gradle.plugin.avro.GenerateAvroJavaTask) {
    source("${buildDir}/src/main/avro")
    outputDir = file("dest/avro")
    outputs.upToDateWhen { false }
}

I am getting the following output 
> Task :generateAvroJava
Task ':generateAvroJava' is not up-to-date because:
  Executed with '--rerun-tasks'.
Found 1 files
Processed src\main\avro\Breed.avsc
:generateAvroJava (Thread[Task worker for ':',5,main]) completed. Took 0.538 secs.
:compileJava (Thread[Task worker for ':' Thread 3,5,main]) started.

The task is showing as completed but I do not see any generated java files in the dest/avro folder.
