### ISSUE TITLE
Support for gradle cache

### ISSUE THREAD

**Issue by dcabasson** [commercehub-oss/gradle-avro-plugin#48]
Looks like the plugin is not currently supporting use of the gradle cache. Do you have any plans to move in a direction where tasks will be gradle cache compatible? Would you be interested in a PR to add such support to the plugin?

**Comment by davidmc24** [comment]
This is the first I've heard of it not supporting the gradle cache, or there potentially being anything plugins need to do to be compatible.  As such, I wouldn't say that I have any plans, but I'm definitely open to considering changes in that direction.

A pull request would be welcome, especially if it includes test support to demonstrate in what way it's currently deficient, so that we can avoid regressions in the future.

**Comment by dcabasson** [comment]
Tasks need to opt-in for gradle cache :
https://docs.gradle.org/current/userguide/build_cache.html#sec:task_output_caching_details

I was looking at GenerateAvroJavaTask and it's definitely not annotated with **@CacheableTask** so that makes it not cacheable.

Test are a bit tricky as it usually requires more than one run. Let me whip up a quick demo of what the issue I am seeing is. I am not sure how we will automate but at least this will be a starting point.

**Comment by davidmc24** [comment]
Thank you for the reference information.  A demonstration is fine, just to make sure we're talking about the same thing, even if we can't automate it or make it part of the test corpus.

**Comment by davidmc24** [comment]
Thank you for the example in #49.  I now clearly understand what we're talking about.  If you're interested in working on a pull request, that would be wonderful.  If not, I should have time to do some analysis on this and either implement support, or have a specific reason why support seems difficult, by the end of next week.
