### ISSUE TITLE
Support for custom java mapping

### ISSUE THREAD

**Issue by doriath2006** [commercehub-oss/gradle-avro-plugin#63]
I request for support for mapping for specified data type like here:
https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/reflect/package-summary.html
`{"type": "int", "java-class": "java.lang.Short"}`

**Comment by davidmc24** [comment]
Hi!  Thanks for the feature request.  This plugin is oriented around the workflow of leveraging the upstream Avro project's capabilities to generate Java classes based on Avro schema/protocol/IDL definitions.  As such, we're sometimes limited by the capabilities that the upstream library provides (in particular, in [SpecificCompiler](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/compiler/specific/SpecificCompiler.html).

This appears to be one such instance.  It looks to me like SpecificCompiler supports some, but not all, of the example uses of `java-class`/`java-element` declarations given in the documentation page you cited.  Those were examples specific to [ReflectDatumReader](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/reflect/ReflectDatumReader.html)/[ReflectDatumWriter](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/reflect/ReflectDatumWriter.html), which is a different model of using Avro.

Here are some options for you:

* Request that the Avro project enhance their support for `java-class`/`java-element` in the SpecificCompiler and/or contribute such support yourself to the Avro project
* Instead of using this plugin, write Java classes to map to your Avro data yourself and use ReflectDataumReader/Writer to interact with them
* Use the default type mappings in the Avro schema, and wrap the generated Avro classes to provide the desired types
* Use the Avro code generator, but then perform manual tweaks to the generated source to apply the desired types that can't be expressed in the schema currently.
