### ISSUE TITLE
Unable to generate .avsc with plugin version 0.8.0

### ISSUE THREAD

**Issue by nshah99** [commercehub-oss/gradle-avro-plugin#71]
Hi, we are using 0.8.0 because the consumers of our generated POJOs are fixed on using 1.7.x due to the bug in https://issues.apache.org/jira/browse/AVRO-1810.

We have a requirement to provide POJOs as well as the .avsc files (which we expect to generate from the .avdl files).

But I cannot seem to find the task which is supposed to do that in 0.8.0. Is there something I am missing here ?

**Comment by davidmc24** [comment]
A stand-alone task to generate .avsc files from .avdl files wasn't added to the plugin until plugin version 0.15.0 in response to issue #56.  If you're maintaining your own fork derived from version 0.8.0 of the plugin, you could likely backport https://github.com/commercehub-oss/gradle-avro-plugin/blob/master/src/main/java/com/commercehub/gradle/plugin/avro/GenerateAvroSchemaTask.java to add this functionality to your fork.

It looks like the AVRO ticket you linked will supposedly be fixed in Avro 1.9.0.  If so, perhaps once Avro 1.9.0 is released you'll be able to upgrade.  Thanks to https://github.com/rocketraman, I expect we'll be able to publish a 1.9.0-compatible release shortly after the Avro version is released, based on pull request #70.

**Comment by nshah99** [comment]
That's great to hear. We are also eagerly waiting for avro 1.9. 

For now we have backported the changes and it is working as expected.

Thanks for the help.
