### ISSUE TITLE
[QUESTION] What might be the cause of a build failure with "Variable $velocityCount has not been set..."

### ISSUE THREAD

**Issue by edgarwhipple** [commercehub-oss/gradle-avro-plugin#73]
I'm trying to switch to a new gradle template on a project that previously built successfully.

What might be missing or incorrectly configured here?

```
$ ./gradlew build --info
Initialized native services in: /Users/ewhipple/.gradle/native
The client will now receive all logging from the daemon (pid: 13324). The daemon log file: /Users/ewhipple/.gradle/daemon/5.4/daemon-13324.out.log
Starting 51st build in daemon [uptime: 3 hrs 18 mins 57.95 secs, performance: 99%, non-heap usage: 47% of 268.4 MB]
Using 8 worker leases.
Starting Build
Settings evaluated using settings file '/Users/ewhipple/Workspace/udp.UdbSchemas/settings.gradle'.
Projects loaded. Root project using build file '/Users/ewhipple/Workspace/udp.UdbSchemas/build.gradle'.
Included projects: [root project 'udp.UdbSchemas']

> Configure project :
Evaluating root project 'udp.UdbSchemas' using build file '/Users/ewhipple/Workspace/udp.UdbSchemas/build.gradle'.
Reckoned version: 1.1.0-SNAPSHOT
All projects evaluated.
Selected primary task 'build' from project :
Tasks to be executed: [task ':generateAvroProtocol', task ':generateAvroJava', task ':compileJava', task ':processResources', task ':classes', task ':jar', task ':javadoc', task ':javadocJar', task ':shadowJar', task ':sourceJar', task ':assemble', task ':dependencyCheckAnalyze', task ':generateTestAvroProtocol', task ':generateTestAvroJava', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':test', task ':jacocoTestReport', task ':jacocoTestCoverageVerification', task ':spotbugsMain', task ':check', task ':build']
:generateAvroProtocol (Thread[Execution worker for ':',5,main]) started.

> Task :generateAvroProtocol NO-SOURCE
Skipping task ':generateAvroProtocol' as it has no source files and no previous output files.
:generateAvroProtocol (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.
:generateAvroJava (Thread[Execution worker for ':',5,main]) started.

> Task :generateAvroJava FAILED
Caching disabled for task ':generateAvroJava' because:
  Build cache is disabled
Task ':generateAvroJava' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Found 3 files
Processed src/main/avro/udp/UdbSchemas/EntryType.avsc
Variable $velocityCount has not been set at /org/apache/avro/compiler/specific/templates/java/classic/record.vm[line 82, column 150]
:generateAvroJava (Thread[Execution worker for ':',5,main]) completed. Took 0.042 secs.
Closing Git repo: /Users/ewhipple/Workspace/udp.UdbSchemas/.git
Closing Git publish repo: /Users/ewhipple/Workspace/udp.UdbSchemas/build/gitPublish

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateAvroJava'.
> Variable $velocityCount has not been set at /org/apache/avro/compiler/specific/templates/java/classic/record.vm[line 82, column 150]

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s
1 actionable task: 1 executed
```

**Comment by davidmc24** [comment]
I'm not sure what you mean by "a new gradle template".

What I'm seeing here is a Gradle project with the gradle Avro plugin applied, failing because the velocity templates being used by the Avro specific compiler (the part of the upstream Avro project that creates Java classes from Avro schema) depend on a variable `$velocityCount` which hasn't been set.  This usually occurs because the templates are out-of-synch with the version of Avro being used to run the generation process.

This usually happens when you're using custom Avro templates via the `avro.templateDirectory` setting in your build file, or the `org.apache.avro.specific.templates` System property.  Assuming you are doing so, and have recently updated either the version of the gradle-avro-plugin (which may update the version of Avro used for generation) or updated the custom Avro templates themselves.

I recommend you confirm which version of the gradle-avro-plugin you're using, check which version of Avro it uses in the changelog (0.11.0 and up are currently all Avro 1.8.2; the next version will likely be 1.9.0), and then base your custom templates on the version of the templates included in that version.

The upstream templates can be found [here](https://github.com/apache/avro/tree/master/lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic); switch to a different tag as needed for the desired version.

**Comment by edgarwhipple** [comment]
Thank you for the alacritous response. Now I know what to look for and
where.

On May 1, 2019, at 6:59 AM, David M. Carr <notifications@github.com> wrote:

I'm not sure what you mean by "a new gradle template".

What I'm seeing here is a Gradle project with the gradle Avro plugin
applied, failing because the velocity templates being used by the Avro
specific compiler (the part of the upstream Avro project that creates Java
classes from Avro schema) depend on a variable $velocityCount which hasn't
been set. This usually occurs because the templates are out-of-synch with
the version of Avro being used to run the generation process.

This usually happens when you're using custom Avro templates via the
avro.templateDirectory setting in your build file, or the
org.apache.avro.specific.templates System property. Assuming you are doing
so, and have recently updated either the version of the gradle-avro-plugin
(which may update the version of Avro used for generation) or updated the
custom Avro templates themselves.

I recommend you confirm which version of the gradle-avro-plugin you're
using, check which version of Avro it uses in the changelog (0.11.0 and up
are currently all Avro 1.8.2; the next version will likely be 1.9.0), and
then base your custom templates on the version of the templates included in
that version.

The upstream templates can be found here
<https://github.com/apache/avro/tree/master/lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic>;
switch to a different tag as needed for the desired version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/commercehub-oss/gradle-avro-plugin/issues/73#issuecomment-488289410>,
or mute the thread
