### ISSUE TITLE
Default Java Package for Avro schema having empty namespace

### ISSUE THREAD

**Issue by viralpatel** [commercehub-oss/gradle-avro-plugin#81]
Current implementation generates Java classes under package specified by `namespace` in avro schema. 

For some of the edge cases where namespace is not defined in avro schema, the generated java class does not have any package making them unusable. This is an edge case which we are currently suffering since existing avro schemas are having empty namespaces.

As a workaround, we can define a custom property `defaultPackageName` which the generator uses to specify package name in case `namespace` is not defined. If namespace is defined it can override this property and generate classes under the namespace.

**Comment by viralpatel** [comment]
I just realized plugin uses Avro Java Compiler to generate the code. So this might not be in scope for this plugin.

https://github.com/apache/avro/blob/master/lang/java/compiler

Happy to close this and explore other options for workaround!

**Comment by davidmc24** [comment]
@viralpatel Correct, this plugin uses the compiler provided by the Avro project.  I don't think that this form of schema transformation is in-scope for this Gradle plugin.  If the upstream Avro compiler adds an option to specify a transformation like this, I'd be happy to expose it so that it can be accessed from the plugin.

As a potential other approach for workaround, you could consider defining a custom task in your build file to do this.  If you're working with JSON schema files, you wouldn't even necessarily need to use the Avro libraries to parse/write the transformed files.  Here's a quick and dirty example of the technique:

### build.gradle

```groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.fasterxml.jackson.core:jackson-databind:2.9.9.3'
    }
}

task transformAvroNamespace(type: Copy) {
    from 'src/raw/avro'
    into 'src/main/avro'
    filter OverrideNamespaceFilter
}

class OverrideNamespaceFilter extends FilterReader {
    static final String DEFAULT_NAMESPACE = 'myname'

    OverrideNamespaceFilter(Reader input) {
        super(new StringReader(transform(input)))
    }
    
    static String transform(Reader input) {
        def mapper = new com.fasterxml.jackson.databind.ObjectMapper().enable(com.fasterxml.jackson.databind.SerializationFeature.INDENT_OUTPUT)
        def rootNode = mapper.readTree(input)
        if (!rootNode.hasNonNull('namespace')) {
            rootNode.put('namespace', DEFAULT_NAMESPACE)
        }
        return mapper.writeValueAsString(rootNode)
    }
}
```

**Comment by aheiss1** [comment]
# @viralpatel @davidmc24  nice job you two.  Love the work around and catch on which compiler.
